"""
DOCX generation utilities for impact stories
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import io


def generate_docx(story_content, tone, length):
    """
    Generate a Microsoft Word document with the impact story
    
    Args:
        story_content (str): The generated story text
        tone (str): The tone used for generation
        length (str): The length setting used
    
    Returns:
        bytes: DOCX file content as bytes
    """
    
    # Create a new Document
    doc = Document()
    
    # Set document margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Add title
    title = doc.add_heading('AI Storytelling', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.color.rgb = RGBColor(30, 64, 175)  # Blue color
    title_run.font.size = Pt(28)
    
    # Add subtitle
    subtitle = doc.add_paragraph('Personalized Impact Narrative')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.runs[0]
    subtitle_run.font.size = Pt(14)
    subtitle_run.font.italic = True
    subtitle_run.font.color.rgb = RGBColor(100, 116, 139)  # Gray color
    
    # Add spacing
    doc.add_paragraph()
    
    # Add metadata
    generation_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    meta_text = f"Generated on {generation_date} | Tone: {tone} | Length: {length}"
    meta = doc.add_paragraph(meta_text)
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.runs[0]
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(148, 163, 184)  # Light gray
    
    # Add horizontal line
    doc.add_paragraph('_' * 80)
    
    # Add spacing
    doc.add_paragraph()
    
    # Add story content
    paragraphs = story_content.split('\n')
    for para_text in paragraphs:
        if para_text.strip():
            para = doc.add_paragraph(para_text.strip())
            para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            para_run = para.runs[0]
            para_run.font.size = Pt(12)
            para_run.font.name = 'Calibri'
            
            # Add spacing between paragraphs
            para_format = para.paragraph_format
            para_format.space_after = Pt(10)
    
    # Add spacing before footer
    doc.add_paragraph()
    doc.add_paragraph()
    
    # Add footer
    footer = doc.add_paragraph('Generated by IAC Impact Story AI')
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.runs[0]
    footer_run.font.size = Pt(9)
    footer_run.font.italic = True
    footer_run.font.color.rgb = RGBColor(148, 163, 184)
    
    # Save to BytesIO buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    
    return buffer.getvalue()
