"""
PDF generation utilities for impact stories
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from datetime import datetime
import io


def generate_pdf(story_content, tone, length):
    """
    Generate a professional PDF document with the impact story
    
    Args:
        story_content (str): The generated story text
        tone (str): The tone used for generation
        length (str): The length setting used
    
    Returns:
        bytes: PDF file content as bytes
    """
    
    # Create a BytesIO buffer
    buffer = io.BytesIO()
    
    # Create the PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#1E40AF',
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    # Subtitle style
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor='#64748B',
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    
    # Body style
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=12,
        fontName='Helvetica'
    )
    
    # Metadata style
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor='#94A3B8',
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    # Add title
    title = Paragraph("AI Storytelling", title_style)
    elements.append(title)
    
    # Add subtitle
    subtitle = Paragraph("Personalized Impact Narrative", subtitle_style)
    elements.append(subtitle)
    elements.append(Spacer(1, 0.3*inch))
    
    # Add metadata
    generation_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    meta_text = f"Generated on {generation_date} | Tone: {tone} | Length: {length}"
    meta = Paragraph(meta_text, meta_style)
    elements.append(meta)
    elements.append(Spacer(1, 0.4*inch))
    
    # Add story content
    # Split into paragraphs and add each
    paragraphs = story_content.split('\n')
    for para in paragraphs:
        if para.strip():
            p = Paragraph(para.strip(), body_style)
            elements.append(p)
    
    # Add footer spacer
    elements.append(Spacer(1, 0.5*inch))
    
    # Add footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor='#94A3B8',
        alignment=TA_CENTER,
        fontName='Helvetica-Oblique'
    )
    footer = Paragraph("Generated by IAC Impact Story AI", footer_style)
    elements.append(footer)
    
    # Build PDF
    doc.build(elements)
    
    # Get the PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
